### PR TITLE
fix(types): A few more promisified method overloads

### LINKED ISSUE #131: TypeScript: Add proper Promise overloads to all methods
At this time there are still several methods that do not have a properly promisified type signature, see e.g. 
https://github.com/googleapis/nodejs-dns/blob/89623ec01daa83d9582919d1642afd37b2bcd48f/src/zone.ts#L366-L368
This issue is meant to track progress on adding overloads for all methods in this project.

### PR DESCRIPTION
**Pull request by carnesen**
Fixes #131 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: src/zone.ts [hunk 1]
```diff
@@ -966,9 +959,11 @@ class Zone extends ServiceObject {
  *   const apiResponse = data[1];
  * });
  */
-import(localPath: string, callback: CreateChangeCallback) {fs.readFile(localPath, 'utf-8', (err, file) => {
+import(localPath: string): Promise<CreateChangeResponse>;
+import(localPath: string, callback: CreateChangeCallback): void;
+import(localPath: string, callback?: CreateChangeCallback): void|Promise<CreateChangeResponse> {fs.readFile(localPath, 'utf-8', (err, file) => {
```
Comment (JustinBeckwith) [inline src/zone.ts]: The formatting here seems weird 🤷‍♂️

Comment (carnesen) [reply src/zone.ts]: Indeed it does. Filed previously as https://github.com/google/ts-style/issues/214

**Comment by JustinBeckwith** [comment]
Thanks for the awesome PRs!
